[tool.poetry]
name = "hypermodern-python-tuto"
version = "0.1.0"
description = "Repo to follow the Claudio Jolowicz's tutorial about Hypermodern Python (https://cjolowicz.github.io/posts/hypermodern-python-01-setup/)"
authors = ["le-chartreux <le-chartreux-vert@protonmail.com>"]
readme = "README.md"
packages = [{include = "hypermodern_python", from = "src"}]
license = "MIT"
homepage = "https://github.com/le-chartreux/hypermodern-python-tuto"
repository = "https://github.com/le-chartreux/hypermodern-python-tuto"
keywords = ["hypermodern"]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
requests = "^2.28.2"

[tool.poetry.scripts]
hypermodern-python = "hypermodern_python.__main__:main"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
pytest-cov = "^4.0.0"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["hypermodern_python"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
