name: nox tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: install nox
      run: pip install nox==2022.11.21
    - name: install poetry
      run: pip install poetry==1.3.2
    - name: run nox
      run: nox --pythons ${{ matrix.python-version }}
