name: nox tests
on: push
jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ['3.10', '3.11']
        os: [ubuntu-latest]

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: install nox
      run: pip install nox==2022.11.21
    - name: install poetry
      run: pip install poetry==1.3.2
    - name: run nox
      run: nox --pythons ${{ matrix.python-version }}
