name: release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: x64
    - name: install nox
      run: pip install nox==2022.11.21
    - name: install poetry
      run: pip install poetry==1.3.2
    - name: run nox
      run: nox --pythons '3.11'
    - run: poetry build
    - run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
