name: release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
    - uses: actions/checkout@v3
    - name: Set up Python
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: x64
    - name: install dependencies
      run: |
        pip install --upgrade pip
        pip install nox==2022.11.21 install poetry==1.3.2
    - name: run nox
      run: nox --pythons '3.11'
    - name: build package
      run: poetry build
    - name: publish package to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: poetry publish --username=__token__ --password="$PYPI_TOKEN"
