name: TestPyPI
on:
  push:
    branches:
      - master
jobs:
  test_pypi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
    - uses: actions/checkout@v3
    - name: Set up Python
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: x64
    - name: install dependencies
      run: |
        pip install --upgrade pip
        pip install poetry==1.3.2
    - name: setting the version to <version>.dev.<timestamp>
    - run: >-
        poetry version patch &&
        version=$(poetry version | awk '{print $2}') &&
        poetry version $version.dev.$(date +%s)
    - name: build package
      run: poetry build
    - name: publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
